Feat/my balances flow
zignaly-open/zigraffle pull request #134
Opened 2022-08-25 08:22 UTC by german-schneck

2022-08-25 09:05 UTC, german-schneck commented
@strrife @NataliaAvila-PM  

Ready to review.

Thanks.

2022-08-25 09:12 UTC, german-schneck commented
@strrife @NataliaAvila-PM  

Ready to review.

Thanks.

2022-08-29 15:01 UTC, german-schneck commented on packages/zignaly-ui/src/index.ts
> +export { customSort } from "utils/numbers";
changed to sortByValue

2022-08-29 15:01 UTC, german-schneck commented on packages/zignaly-ui/src/utils/strings.ts
> +export const isEmpty = (text: string) => {
removed.

2022-08-29 15:49 UTC, german-schneck commented
I have brought changes from master and I am having problems with the checks.

2022-09-01 08:14 UTC, german-schneck commented
@strrife Hi, give me a feedback when you can! Thanks

2022-09-05 16:09 UTC, german-schneck commented
@NataliaAvila-PM @strrife Review when you can, please.

Thanks.

2022-09-07 02:43 UTC, strrife requested changes

2022-09-07 02:43 UTC, strrife commented on packages/ps2/package.json
> +    "react-table": "^7.8.0",
@german-schneck I think we've discussed that IRL, we should not add it as a dependency. My changes for table types should be enough.

2022-09-07 02:43 UTC, strrife commented on packages/ps2/.eslintignore
> +src/react-table-config.d.ts
if it should be added to the codebase, it certainly should not go to the ps2 project. Zignaly UI only.

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/utils/strings.ts
> +export const isEmpty = (text: string) => {
I do not see it removed.

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/utils/numbers.ts
> +  firstNumber: string | number,
no problem with having them called a and b

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/utils/numbers.ts
> +// Dependencies
well, I still see it here

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/CheckBox/index.tsx
> +  onChange = () => null,
woundnt it be easier to mark this as optional in the type definitions and then call it not with `onChange(value)` but with `onChange?.(value)`?

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/ExpandableInput/index.tsx
> +function ExpandableInput({ icon, placeholder = "", value = "", onChange }: ExpandableInputProps) {
* missing return type
* still using the // state // refs 
* what is this component?

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/ExpandableInput/styles.ts
> +// Dependencies
```suggestion
```

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/ExpandableInput/types.ts
> +  onChange: any;
@german-schneck you should **not** be using any

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/components/Portal/index.tsx
> +// Dependencies
```suggestion
```

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/components/Portal/index.tsx
> +// Types
```suggestion
```

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/components/Portal/index.tsx
> +  return <InitPortal>{children}</InitPortal>;
any particualr reason to not use react-portal directly?

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/components/Portal/types.ts
> +  children: any;
please stop using any

2022-09-07 02:43 UTC, strrife commented on packages/ps2/src/react-table-config.d.ts
> +import {
does this still cause issues with the types in the dashboard?

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/index.tsx
> +  const requestAniRef = useRef<any>();
please forget about the existence of the word `any`

2022-09-07 02:43 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/index.tsx
> +      {isActiveDropdown && (
why not use mui dropdown?

2022-09-07 09:03 UTC, german-schneck commented on packages/zignaly-ui/src/components/inputs/IconButton/components/Portal/index.tsx
> +  return <InitPortal>{children}</InitPortal>;
Nope, I brought it over from the previous version without making any changes. I correct it.

2022-09-07 09:08 UTC, german-schneck commented on packages/ps2/src/react-table-config.d.ts
> +import {
If I remove this, I get these errors. Both in my table and yours in dashboard.

<img width="563" alt="Screen Shot 2022-09-07 at 11 05 39" src="https://user-images.githubusercontent.com/15254932/188838904-fdfe33d0-d0a3-48f1-bf8d-82dd38c1e950.png">

2022-09-07 09:56 UTC, german-schneck commented on packages/zignaly-ui/src/components/inputs/IconButton/index.tsx
> +      {isActiveDropdown && (
Because it would require refactoring a component that works and is used in several places right now. Making this change would be time consuming, unless you want @NataliaAvila-PM  to do it.

2022-09-07 11:30 UTC, NataliaAvila-PM commented on packages/zignaly-ui/src/components/inputs/IconButton/index.tsx
> +      {isActiveDropdown && (
right now we have these dropdowns in the deposit modals and the ones in the menus. If we want to change it now it is the time to do it.

2022-09-12 09:59 UTC, german-schneck commented
@strrife You can revalidate it. About react-table-config.d.ts, keep the file because if I delete it, TypeScript starts throwing a lot of errors (including your tables).

What can we do here?

2022-09-12 10:00 UTC, german-schneck commented on packages/zignaly-ui/src/components/inputs/IconButton/index.tsx
> +      {isActiveDropdown && (
Done.

2022-09-12 14:07 UTC, german-schneck commented on packages/zignaly-ui/src/components/inputs/CheckBox/index.tsx
> +  onChange = () => null,
onChange?.(value)

I don't understand that part. onChange is a function, but you say to access it as an object?

2022-09-12 14:37 UTC, german-schneck commented on packages/zignaly-ui/src/components/inputs/ExpandableInput/index.tsx
> +function ExpandableInput({ icon, placeholder = "", value = "", onChange }: ExpandableInputProps) {
Done.

This component has the particularity of expanding and contracting if you write text/make focus. It is implemented in the search engine of my balances, for example.

2022-09-12 14:37 UTC, german-schneck commented on packages/zignaly-ui/src/components/inputs/ExpandableInput/styles.ts
> +// Dependencies
Done

2022-09-12 15:55 UTC, strrife requested changes

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/api.ts
> +    /* Get the myBalances with a reduced data */
```suggestion
```

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/api.ts
> +    /* Get all coins of an exchange */
```suggestion
```

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/components/AccountSelector/index.tsx
> +// Dependencies
```suggestion
```

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/components/AccountSelector/index.tsx
> +   */
```suggestion
```

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/components/AccountSelector/index.tsx
> +  const dropDownRef = useRef(null);
should have type

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/components/AccountSelector/index.tsx
> +                        key={`--exchange-key-${index.toString()}`}
let's have ids here for easier testing pls

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/components/MyBalancesTable/index.tsx
> +   */
```suggestion
```

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/components/MyBalancesTable/index.tsx
> +          <PriceLabel coin={value.symbol} value={value.balanceTotalUSDT} />
we should have USD here, I think

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/components/MyBalancesTable/index.tsx
> +      symbol: coin,
and we do not need the symbol here

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/components/MyBalancesTable/styles.ts
> +// Dependencies
```suggestion
```

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/components/MyBalancesTable/types.ts
> +  };
no need for symbol here

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/use.ts
> +      ]);
what is the point of promise.all?

2022-09-12 15:55 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/ExpandableInput/index.tsx
> +   */
```suggestion
```

2022-09-12 15:55 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/ExpandableInput/index.tsx
> +  const inputRef = useRef(null) as RefObject<HTMLInputElement>;
```suggestion
  const inputRef = useRef<RefObject<HTMLInputElement>>(null);
```

2022-09-12 15:55 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/ExpandableInput/index.tsx
> +        <Input
this should customize and use the zignaly-ui input

2022-09-12 15:55 UTC, strrife commented on packages/ps2/.eslintignore
> +src/react-table-config.d.ts
it should go to zignaly-ui

2022-09-12 15:55 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/ExpandableInput/index.tsx
> +        <Input
so we should use InputText, handle all the expansion-contraction logic in this component but for the input we should re-use InputText from zignaly-ui

2022-09-12 15:55 UTC, strrife commented on packages/zignaly-ui/src/utils/numbers.ts
>    return 0;
return +number2 - +number1;

?

2022-09-12 15:55 UTC, strrife commented on packages/ps2/src/features/myBalances/use.ts
> +  const [, { isFetching: isLoadingAllCoins }] = useLazyAllCoinsQuery();
you can still use the data since it comes in the same object as isFetchign

it's better to aggregate data here

2022-09-12 15:55 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/styles.ts
> +     ${renderSizeProps(props)}
```suggestion
  ${renderSizeProps};
  
  ${(props) => `
```

2022-09-12 15:55 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/index.tsx
> +const IconButton: (props: DropdownProps, innerRef: React.Ref<DropdownHandle>) => JSX.Element = (
pls fix naming

2022-09-12 15:55 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/index.tsx
> +    return disabled ? () => {} : renderDropDown ? handleClick : onClick;
nested ternaries are unreadable evil

2022-09-12 15:55 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/index.tsx
> +    return disabled ? () => {} : renderDropDown ? handleClick : onClick;
if eslint was not highlighting this as an error, please make sure nested ternaries are treated as esline errors

2022-09-12 15:55 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/index.tsx
> +    return disabled ? () => {} : renderDropDown ? handleClick : onClick;
namign is not very telling

2022-09-12 15:55 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/index.tsx
> +      </Menu>
we should not mix components like this. If you need a dropdown triggered by an IconButton component, please arrange them whenever you need them. IconButton should now know anythign about Dropdowns.

2022-09-14 19:08 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/CheckBox/index.tsx
> +  onChange = () => null,
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
pls read the spec

2022-09-14 19:09 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/ExpandableInput/index.tsx
> +function ExpandableInput({ icon, placeholder = "", value = "", onChange }: ExpandableInputProps) {
It still uses a custom input.

2022-09-14 19:10 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/ExpandableInput/index.tsx
> +function ExpandableInput({ icon, placeholder = "", value = "", onChange }: ExpandableInputProps) {
It should be using an already existing component

2022-09-18 06:11 UTC, strrife commented on packages/ps2/src/features/myBalances/use.ts
> +      Object.entries(balances).reduce(
I do not think the table gets rendered once the coins are loaded and the balances are not, I remember that was a requirement

2022-09-18 06:14 UTC, strrife commented on packages/zignaly-ui/src/components/display/Table/types/PagedWithDataTable/index.tsx
> +      </View>
are you sure about moving the below part from the view?

2022-09-18 06:17 UTC, strrife commented on packages/zignaly-ui/src/components/inputs/IconButton/types.ts
> +export type IconButtonHandle = {
we should remove unused types and update existing ones

2022-09-20 13:17 UTC, german-schneck commented on packages/zignaly-ui/src/components/inputs/IconButton/types.ts
> +export type IconButtonHandle = {
Done

2022-09-20 13:18 UTC, german-schneck commented on packages/zignaly-ui/src/components/display/Table/types/PagedWithDataTable/index.tsx
> +      </View>
What do you mean?

2022-09-20 22:42 UTC, german-schneck commented on packages/ps2/src/features/myBalances/components/AccountSelector/index.tsx
> +        dropDownRef.current?.closeDropDown();
Solved

2022-09-20 22:42 UTC, german-schneck commented on packages/ps2/src/features/myBalances/components/AccountSelector/index.tsx
> +  const dropDownRef: React.Ref<DropDownHandle> = useRef(null);
Solved

2022-09-20 23:19 UTC, german-schneck commented on packages/ps2/src/features/myBalances/components/AccountSelector/index.tsx
> +                    exchanges.map((exchange: Exchange, index: number) => (
Done

2022-09-21 09:17 UTC, strrife requested changes

2022-09-21 09:17 UTC, strrife commented on packages/zignaly-ui/src/components/display/Expandable/index.tsx
> +    </Layout>
You tried to make this component kind of universal by allowing children in. But:
1. it's not like there will be too many usages for this aside from the one intended
2. this is still not abstracted from the input, i.e. still has value that is supposed to be a string

2022-09-21 09:17 UTC, strrife commented on packages/zignaly-ui/src/components/display/DropDown/index.tsx
> +          {content}
why do we need a custom inner content? I understand we may want to have a base component and maybe some that is easier to use, but why not follow this https://mui.com/material-ui/react-menu/ ?

If you want to be able to customize whay opens a dropdown, why not make the <component an anchor?

2022-09-21 09:17 UTC, strrife commented on packages/ps2/src/features/myBalances/components/MyBalancesTable/index.tsx
> +            />
there's no point in creating Expandable component is the expansion logic is handled outside of it

2022-09-21 11:15 UTC, german-schneck commented on packages/zignaly-ui/src/components/display/DropDown/index.tsx
> +          {content}
Because I see that Menu is oriented to just menus, and DropDown is used in many other ways. For what the suitable component to use it of generic form is Popover.

2022-09-21 11:17 UTC, german-schneck commented on packages/ps2/src/features/myBalances/components/MyBalancesTable/index.tsx
> +            />
So what do you suggest?

2022-09-21 11:20 UTC, german-schneck commented on packages/ps2/src/features/myBalances/use.ts
> +      Object.entries(balances).reduce(
I don't understand your point.

2022-09-21 11:21 UTC, german-schneck commented on packages/ps2/src/features/myBalances/components/AccountSelector/styles.ts
> +  .internalName {
This seems to have been removed already.

2022-09-27 02:01 UTC, strrife approved these changes
Good luck

2022-09-27 02:14 UTC, merged